-- AUTO-GENERATED by build_pipeline.py -- do not hand-edit.
-- Source: mangos.achievement_retirement (1 rows)

AchieverStaticData = AchieverStaticData or {}

AchieverStaticData.retirements = {
	[4826] = { replacement = 4828, patch = 1 },
}
