-- AUTO-GENERATED by build_pipeline.py -- do not hand-edit.
-- Source: mangos.achievement_reward_locale (219 rows)

AchieverStaticData = AchieverStaticData or {}

AchieverStaticData.rewardLocales = {
	[46] = {
		frFR = { subject = "", text = "" },
	},
	[230] = {
		frFR = { subject = "", text = "" },
	},
	[432] = {
		frFR = { subject = "", text = "" },
	},
	[456] = {
		frFR = { subject = "", text = "" },
	},
	[614] = {
		deDE = { subject = "Für die Allianz!", text = "Krieg überzieht unsere Länder. Nur die tapfersten aller Helden wagen es, der Horde dort einen Schlag zu versetzen, wo es wehtut. Ihr gehört zu eben diesen Helden.$B$BDer Schlag, den Ihr der Führung der Horde versetzt habt, bereitet unseren Weg für den finalen Angriff. Die Horde wird sich vor der Macht der Allianz verbeugen.$B$BEure Taten bleiben nicht ungewürdigt. Reitet mit Stolz!$B$B--Euer König" },
		esES = { subject = "¡Por la Alianza!", text = "La guerra hace estragos en nuestras tierras. Solo los héroes más valientes se atreven a desafiar a la Horda donde más les duele. Estás entre esos héroes.$B$BLos golpes que le has dado a los líderes de la Horda abrirán la puerta a nuestro asalto final. La Horda se inclinará ante el poder de la Alianza.$B$BTus acciones no quedarán sin recompensa. ¡Sigue adelante con orgullo!$B$B--Tu rey" },
		esMX = { subject = "¡Por la Alianza!", text = "La guerra hace estragos en nuestras tierras. Solo los héroes más valientes se atreven a desafiar a la Horda donde más les duele. Estás entre esos héroes.$B$BLos golpes que le has dado a los líderes de la Horda abrirán la puerta a nuestro asalto final. La Horda se inclinará ante el poder de la Alianza.$B$BTus acciones no quedarán sin recompensa. ¡Sigue adelante con orgullo!$B$B--Tu rey" },
		frFR = { subject = "Pour l'Alliance !", text = "La guerre fait rage sur nos terres. Seuls les héros les plus courageux osent frapper la Horde en ses points les plus sensibles. Vous êtes l'un d'eux.\n\nLes coups que vous avez portés au commandement de la Horde vont nous permettre de lancer notre assaut final. La Horde fléchira sous la puissance de l'Alliance.\n\nVos actes seront récompensés. Chevauchez avec fierté !\n\n— Votre roi" },
		zhCN = { subject = "为了联盟！", text = "战争的怒火席卷了整个大陆。只有最勇敢的人才敢发动斩首行动给敌人以迎头痛击。而你，就是这样的英雄。$B$B你和你的同伴们的行动将给我们最终的胜利带来不可估量的影响。部落在我们联盟的力量面前必将屈服。$B$B你的所作所为不会没有回报，这就是奖励给你的坐骑，自豪地骑上去吧。$B$B为了联盟！$B$B--你的国王" },
	},
	[619] = {
		deDE = { subject = "Für die Horde!", text = "In Zeiten großer Unruhen erheben sich wahre Helden aus dem Elend. Ihr seid ein solch großer Held.$B$BDer Krieg steht vor der Tür. Eure Bemühungen werden unsere Sache in Azeroth voranbringen. Eure großen Taten werden belohnt werden. Nehmt diese Belohnung von Orgrimmar und reitet zum Ruhm.$B$BFür die Horde!$B$BKriegshäuptling Thrall" },
		esES = { subject = "¡Por la Horda!", text = "En esta época de gran agitación, los verdaderos héroes surgen de la miseria. Eres uno de esos grandes héroes.$B$BLa guerra está sobre nosotros. Tus esfuerzos promoverán nuestra causa en Azeroth. Tus grandes hazañas serán recompensadas. Toma este premio de Orgrimmar y cabalga hacia la gloria.$B$B¡Por la Horda!$B$BJefe de Guerra Thrall" },
		esMX = { subject = "¡Por la Horda!", text = "En esta época de gran agitación, los verdaderos héroes surgen de la miseria. Eres uno de esos grandes héroes.$B$BLa guerra está sobre nosotros. Tus esfuerzos promoverán nuestra causa en Azeroth. Tus grandes hazañas serán recompensadas. Toma este premio de Orgrimmar y cabalga hacia la gloria.$B$B¡Por la Horda!$B$BJefe de Guerra Thrall" },
		frFR = { subject = "Pour la Horde !", text = "En ces temps troublés, nos souffrances engendrent de vrais héros. Vous êtes l'un d'eux.\n\nNous sommes en guerre. Vos efforts soutiennent notre cause en Azeroth. Vos hautes actions seront récompensées. Prenez ce prix d'Orgrimmar et chevauchez vers la gloire.\n\nPour la Horde !\n\nChef de guerre Thrall" },
		zhCN = { subject = "为了部落！", text = "在这次行动中，伟大的勇士从苦难困苦中昂首站了起来。你就是其中之一。$B$B战争就在我们面前，你的努力会为我们在艾泽拉斯的征程上画上浓重的一笔。你的勇敢必须要得到奖励， 请收下这来自奥格瑞玛的奖励，并且彰显 你的果敢！$B$B为了部落！$B$B大酋长萨尔" },
	},
	[714] = {
		frFR = { subject = "", text = "" },
	},
	[762] = {
		frFR = { subject = "", text = "" },
	},
	[870] = {
		frFR = { subject = "", text = "" },
	},
	[871] = {
		frFR = { subject = "", text = "" },
	},
	[876] = {
		deDE = { subject = "Brutaler Kämpfer", text = "Ihr habt ein ganz schönes Händchen dafür Euch in diese Arena zu werfen. Behaltet das bei. Tragt es mit Stolz. Jetzt geht wieder rein und zeigt ihnen, wie es gemacht wird! $B$BOnkel Sal" },
		esES = { subject = "Te he estado mirando $gniño:niña;", text = "Tienes una gran habilidad para vencer en esa arena. Guarda esto. Úsalo con orgullo. ¡Ahora vuelve y enséñales cómo se hace!$B$BTío sal" },
		esMX = { subject = "Te he estado mirando $gniño:niña;", text = "Tienes una gran habilidad para vencer en esa arena. Guarda esto. Úsalo con orgullo. ¡Ahora vuelve y enséñales cómo se hace!$B$BTío sal" },
		frFR = { subject = "Je vous surveille , enfent.", text = "" },
		zhCN = { subject = "我一直在关注着你，孩子。", text = "你长期泡在竞技场的行为给你的格斗技巧带来了很大的提升，$n。 收下这件战袍，然后穿上它。自豪地走上街，让别人看看你洒过的汗水以及收获的果实！$B$B赛尔叔叔" },
	},
	[907] = {
		frFR = { subject = "", text = "" },
	},
	[913] = {
		frFR = { subject = "", text = "" },
	},
	[942] = {
		frFR = { subject = "", text = "" },
	},
	[943] = {
		frFR = { subject = "", text = "" },
	},
	[945] = {
		frFR = { subject = "", text = "" },
	},
	[948] = {
		frFR = { subject = "", text = "" },
	},
	[953] = {
		frFR = { subject = "", text = "" },
	},
	[978] = {
		frFR = { subject = "", text = "" },
	},
	[1015] = {
		frFR = { subject = "", text = "" },
	},
	[1021] = {
		deDE = { subject = "Ganz schön erfolgreich", text = "Mir ist aufgefallen, was für eine eindrucksvolle Sammlung an Wappenröcken Ihr mit der Zeit gesammelt habt. Ihr könnt diesen hier genauso gut Eurer Sammlung hinzufügen. Er hat in meinem Schrank nur Staub angesetzt." },
		esES = { subject = "$gCompleto:Completa; $gTriunfador:Triunfadora;", text = "No pude evitar darme cuenta de la excelente colección de tabardos que has conseguido reunir a lo largo de las temporadas. También podrías agregar este a tu colección. Simplemente ha estado acumulando polvo en mi armario." },
		esMX = { subject = "$gCompleto:Completa; $gTriunfador:Triunfadora;", text = "No pude evitar darme cuenta de la excelente colección de tabardos que has conseguido reunir a lo largo de las temporadas. También podrías agregar este a tu colección. Simplemente ha estado acumulando polvo en mi armario." },
		frFR = { subject = "", text = "" },
		zhCN = { subject = "相当成功！", text = "你日复一日，年复一年的收集战袍，让我不由得注意到了你。我想，你也会很乐意收下这件吧， 嗯，或许，战袍在我这里更容易沾染灰尘。" },
	},
	[1038] = {
		frFR = { subject = "", text = "" },
	},
	[1039] = {
		frFR = { subject = "", text = "" },
	},
	[1174] = {
		frFR = { subject = "", text = "" },
	},
	[1175] = {
		frFR = { subject = "", text = "" },
	},
	[1250] = {
		deDE = { subject = "Stinkis neues Zuhause", text = "Ich habe gehört, wie gut Ihr Euch um unsere pelzigen Freunde kümmert. Ich hoffe, es macht Euch nichts aus, aber ich muss Stinki ein neues Zuhause verschaffen. Er weigert sich einfach, friedlich mit den Anderen zu spielen.$B$BBitte stellt sicher, dass er zweimal täglich gefüttert wird. Und, ähm... er hat eine Schwäche für schwarze Katzen.$B$B--Breanni" },
		esES = { subject = "El nuevo hogar de Stinker", text = "Escuché lo bien que cuidas a nuestros amigos peludos. Espero que no te importe, pero debo conseguirle a Stinker un nuevo hogar. Simplemente se niega a jugar bien con los demás.$B$BAsegúrate de alimentarlo dos veces al día. Y umm... tiene algo con los gatos negros.$B$B--Breanni" },
		esMX = { subject = "El nuevo hogar de Stinker", text = "Escuché lo bien que cuidas a nuestros amigos peludos. Espero que no te importe, pero debo conseguirle a Stinker un nuevo hogar. Simplemente se niega a jugar bien con los demás.$B$BAsegúrate de alimentarlo dos veces al día. Y umm... tiene algo con los gatos negros.$B$B--Breanni" },
		frFR = { subject = "", text = "" },
		zhCN = { subject = "臭臭的新家", text = "我听说了你很喜欢养一些毛茸茸小动物的事，我希望你不会介意我给我的臭臭找一个新家吧——它拒绝和我这里的小动物一起玩耍。$B$B如果你收下，请确保一天喂它两次。然后，嗯，它貌似对黑猫挺有兴趣的，你懂的。$B$B--布琳妮" },
	},
	[1400] = {
		frFR = { subject = "", text = "" },
	},
	[1402] = {
		frFR = { subject = "", text = "" },
	},
	[1516] = {
		frFR = { subject = "", text = "" },
	},
	[1563] = {
		frFR = { subject = "", text = "" },
	},
	[1656] = {
		frFR = { subject = "", text = "" },
	},
	[1657] = {
		frFR = { subject = "", text = "" },
	},
	[1658] = {
		frFR = { subject = "", text = "" },
	},
	[1681] = {
		deDE = { subject = "Grüße aus Darnassus", text = "Eure Erfolge waren tiefgreifend und weitreichend. Azeroth profitiert bei den jüngsten Tumulten in großem Maße von jenen, die das Land vom Bösen zu befreien suchen.$B$BNur diejenigen, die sich die Zeit nehmen, unser Land kennen zu lernen, verstehen das Opfer der Gefallenen und den Wert unserer Helden. Ihr seid ein solcher Held. Hoffentlich werdet Ihr Euch noch in vielen Jahren an die Geschichten Eurer Abenteuer erinnern können.$B$BIm Namen der Allianz danke ich Euch, Meister der Lehren." },
		esES = { subject = "Saludos de Darnassus", text = "Tus logros han sido profundos y de gran alcance. Azeroth, con toda la agitación reciente, se beneficia enormemente de aquellos que buscan librar a la tierra del mal.$B$BSolo aquellos que se toman el tiempo de conocer nuestras tierras comprenden los sacrificios de los caídos y el valor de $gnuestros:nuestras; $ghéroes:heroinas;. Eres $guno:una; de esos $ghéroes:heroínas;. Con suerte, se recordarán los relatos de sus aventuras durante los próximos años.$B$BEn nombre de la Alianza, te doy las gracias, Maestro Cultural." },
		esMX = { subject = "Saludos de Darnassus", text = "Tus logros han sido profundos y de gran alcance. Azeroth, con toda la agitación reciente, se beneficia enormemente de aquellos que buscan librar a la tierra del mal.$B$BSolo aquellos que se toman el tiempo de conocer nuestras tierras comprenden los sacrificios de los caídos y el valor de $gnuestros:nuestras; $ghéroes:heroinas;. Eres $guno:una; de esos $ghéroes:heroínas;. Con suerte, se recordarán los relatos de sus aventuras durante los próximos años.$B$BEn nombre de la Alianza, te doy las gracias, Maestro Cultural." },
		frFR = { subject = "", text = "" },
		zhCN = { subject = "来自达纳苏斯的问候", text = "你的成就是意义重大且影响深远的。一直以来饱受折磨的艾泽拉斯因为你的这次行为而摆脱了恶魔的束缚。$B$B只有那些愿意花时间去了解我们土地的人才能明白我们的那些勇士为这片大陆前赴后继的意义，你是其中的一个。 很高兴你能顺利结束你的探险，愿艾露恩祝福着你。$B$B一切为了联盟，感谢你， 博学者。$B$B--泰兰德·语风" },
	},
	[1682] = {
		deDE = { subject = "Grüße aus Donnerfels", text = "Eure Erfolge waren tiefgreifend und weitreichend. Azeroth profitiert bei den jüngsten Tumulten in großem Maße von jenen, die das Land vom Bösen zu befreien versuchen.$B$BNur diejenigen, die sich die Zeit nehmen, unser Land kennen zu lernen, verstehen das Opfer der Gefallenen und den Wert unserer Helden. Ihr seid ein solcher Held. Hoffentlich werdet Ihr Euch noch in vielen Jahren an die Geschichten Eurer Abenteuer erinnern können.$B$BHabt Dank, Meister der Lehren.$B$BFür die Horde!$B$B--Cairne Bluthuf" },
		esES = { subject = "Saludos desde Cima del Trueno", text = "Las noticias de sus logros han viajado lejos. Los vientos de la agitación aúllan a través de nuestras tierras. Aquellos que desafían el mal son nuestra única esperanza.$B$BSolo aquellos que escuchan los vientos comprenden las deudas que nuestros héroes caídos han pagado para proteger a nuestra gente. Que $gun:una; $ghéroe:heroína; como tú viva mucho para contar las historias de tus aventuras. Porque solo entonces recordaremos cuánto tenemos que estar agradecidos.$B$BNuestro agradecimiento es profundo, $gMaestro:Maestra; Cultural.$B$B¡Por la Horda!$B$B--Cairne Pezuña de Sangre" },
		esMX = { subject = "Saludos desde Cima del Trueno", text = "Las noticias de sus logros han viajado lejos. Los vientos de la agitación aúllan a través de nuestras tierras. Aquellos que desafían el mal son nuestra única esperanza.$B$BSolo aquellos que escuchan los vientos comprenden las deudas que nuestros héroes caídos han pagado para proteger a nuestra gente. Que $gun:una; $ghéroe:heroína; como tú viva mucho para contar las historias de tus aventuras. Porque solo entonces recordaremos cuánto tenemos que estar agradecidos.$B$BNuestro agradecimiento es profundo, $gMaestro:Maestra; Cultural.$B$B¡Por la Horda!$B$B--Cairne Pezuña de Sangre" },
		frFR = { subject = "", text = "" },
		zhCN = { subject = "来自雷霆崖的问候", text = "你的故事被广为流传， 犹如一股飓风席卷了整个大陆。 那些敢于和恶魔战斗的人是我们唯一的期望。$B$B只有那些听懂风的语言的人才能明白我们欠那些为保护这片大陆而倒下的勇士们多少。希望你能把你探险的故事告诉更多像你这样活着的年轻人。然后我们就会记起来我们在这个世上有多少需要感谢。$B$B向你致以深深的感谢，博学者，大地母亲与你同在。$B$B为了部落！$B$B--凯恩·血蹄" },
	},
	[1683] = {
		frFR = { subject = "", text = "" },
	},
	[1684] = {
		frFR = { subject = "", text = "" },
	},
	[1691] = {
		frFR = { subject = "", text = "" },
	},
	[1692] = {
		frFR = { subject = "", text = "" },
	},
	[1693] = {
		frFR = { subject = "", text = "" },
	},
	[1707] = {
		frFR = { subject = "", text = "" },
	},
	[1784] = {
		frFR = { subject = "", text = "" },
	},
	[1793] = {
		frFR = { subject = "", text = "" },
	},
	[1956] = {
		deDE = { subject = "Hohe Schule", text = "Herzlichen Glückwunsch zu Eurem Abschluss in den Schulen der arkanen Magie. In Anerkennung Eurer Hingabe lege ich diesen speziellen Buchband bei, der die Serie vervollständigt.$B$BIch denke, dass Ihr diesen Folianten sehr unterhaltsam finden werdet. Doch das dürft Ihr selbst entscheiden.$B$BHochachtungsvoll,$B$BRhonin" },
		frFR = { subject = "Lectures studieuses", text = "Félicitations ! Vous avez terminé d'étudier « Les écoles de magie des arcanes ». En récompense de votre dévouement, veuillez trouver ci-joint le volume spécial qui termine la collection.\n\nJe pense que vous trouverez ce tome particulièrement divertissant. Mais je vous laisse le découvrir par vous-même.\n\nCordialement,\n\nRhonin" },
		zhCN = { subject = "进修", text = "恭喜你顺利完成了在达拉然魔法学院的进修工作。为了鼓励你所获得的成就， 我把这部典籍邮寄给你，希望你能收下。$B$B我想，你应该能知道这份籍的用途。$B$B向你致以真诚的问候。$B$B罗宁" },
	},
	[2051] = {
		frFR = { subject = "", text = "" },
	},
	[2054] = {
		frFR = { subject = "", text = "" },
	},
	[2096] = {
		deDE = { subject = "Der Münzenmeister", text = "Grüße und Glückwünsche dazu, dass Ihr das gesamte Set der Dalaranmünzen gesammelt habt! Als Belohnung Eurer harten Arbeit habe ich diesem Schreiben ein frisch geprägtes Titansiegel von Dalaran beigelegt. Dies ist eine besondere Münze, die wir nur den leidenschaftlichsten aller Sammler verleihen.$B$BIch hoffe, Ihr findet Freude an dieser speziellen Belohnung. Ihr habt Sie Euch verdient!$B$BHochachtungsvoll,$B$BJepetto Spaßbrumm" },
		frFR = { subject = "", text = "" },
		zhCN = { subject = "金币达人", text = "你好，恭喜你成功收集到了达拉然喷泉的所有硬币！ 为了表彰你，我准备把这枚达拉然泰坦神铁徽记赠与你，这是一枚我们只奖励给狂热的硬币收集者的礼物。$B$B希望你会喜欢我这份特殊的礼物，现在，它是你的了！$B$B真挚的问候您。$B耶比托·乔巴斯" },
	},
	[2136] = {
		deDE = { subject = "Ruhm des Helden", text = "Held,$B$BErzählungen der großen Taten, die Ihr seit eurem Eintreffen in Nordend vollbracht habt, sind bis zum Wyrmruhtempel vorgedrungen.$B$BEure Tapferkeit soll nicht unbemerkt bleiben. Bitte aktzeptiert dieses Geschenk im Namen der Aspekte. Mögen wir zusammen Azeroth ein für alle Mal vom Bösen befreien.$B$BAlexstrasza, die Lebensbinderin" },
		esES = { subject = "La gloria $gdel:de la; $ghéroe:heroína;", text = "$gCampeón:Campeona;,$B$BHa llegado al Templo del Reposo del Dragón las grandes hazañas heroicas que has realizado desde que llegaste a Rasganorte.$B$BTu valentía no debe pasar desapercibida. Acepta este regalo en nombre de los Aspectos. Juntos libraremos a Azeroth del mal, de una vez y para siempre.$B$BAlexstrasza la Protectora" },
		esMX = { subject = "La gloria $gdel:de la; $ghéroe:heroína;", text = "$gCampeón:Campeona;,$B$BHa llegado al Templo del Reposo del Dragón las grandes hazañas heroicas que has realizado desde que llegaste a Rasganorte.$B$BTu valentía no debe pasar desapercibida. Acepta este regalo en nombre de los Aspectos. Juntos libraremos a Azeroth del mal, de una vez y para siempre.$B$BAlexstrasza la Protectora" },
		frFR = { subject = "", text = "" },
		zhCN = { subject = "英雄的荣耀！", text = "尊敬的勇士，$B$B你在诺森德英勇战斗的身影以及所获得的成就已经传到了龙眠神殿。$B$B你的勇敢不容忽视，请你务必接受这份礼物，和它一起，我们并肩驱逐诺德德的恶魔，一次抑或永远。$B$B阿莱克丝塔萨，生命缚誓者" },
	},
	[2143] = {
		deDE = { subject = "Führen der Kavalerie", text = "Ich konnte nicht umhin, zu sehen wie gut Ihr mit Tieren umgeht. Bei allem was hier vorgeht, laufen meine Geschäfte besser denn je.$B$BIch nehme nicht an, dass es Euch etwas ausmacht, für mich auf diesen Albinodrachen aufzupassen. Ich habe einfach nicht genug Zeit, mich um all diese Tiere zu kümmern.$B$BViele Grüße.$B$BMei" },
		esES = { subject = "Liderar la caballería", text = "No pude evitar notar lo $gbueno:buena; que eres con el ganado. Con toda la actividad por aquí, el negocio ha ido mejor que nunca para mí. Supongo que no te importaría cuidar de este Draco Albino por mí. Simplemente no tengo suficientes minutos libres en el día para cuidar a todos estos animales.$B$BTuya, Mei" },
		esMX = { subject = "Liderar la caballería", text = "No pude evitar notar lo $gbueno:buena; que eres con el ganado. Con toda la actividad por aquí, el negocio ha ido mejor que nunca para mí. Supongo que no te importaría cuidar de este Draco Albino por mí. Simplemente no tengo suficientes minutos libres en el día para cuidar a todos estos animales.$B$BTuya, Mei" },
		frFR = { subject = "", text = "" },
		zhCN = { subject = "带领骑兵队", text = "我发现你和你的坐骑们相处得好像挺不错的嘛，我每天都要对着这些牲畜简直烦躁死了。我想，你不会介意替我照看下这只白色幼龙吧？我只是抽不出空暇的时间来照顾这么多的坐骑了。$B$B梅尔·弗兰希斯" },
	},
	[2144] = {
		deDE = { subject = "Ein ums andere Mal", text = "Dadurch, dass in der Ferne immer die Kriegstrommeln ertönen, vergessen die Bewohner Azeroths nur allzu leicht all die Dinge, die das Leben zu bieten hat.$B$BIhr habt hingegen mit Eurer Fähigkeit, Euch daran zu erinnern, wofür wir letztlich kämpfen, die Erhabenheit der guten Völker Azeroths bewahrt. Unsere Siege nicht zu feiern wäre eine weitere Form der Niederlage. Denkt immer daran, Feiernder.$B$BMögen andere von Eurem Frohsinn inspiriert werden.$B$BAlextrasza, die Lebensbinderin" },
		esES = { subject = "Una y otra vez", text = "Con los tambores de guerra retumbando a lo lejos, es fácil para los habitantes de Azeroth olvidar todo lo que la vida tiene para ofrecer.$B$BTú, por otro lado, has mantenido la dignidad de las buenas razas de Azeroth con tu habilidad para recordar por qué luchamos. No celebrar nuestras victorias es otra forma de derrota. Recuérdalo bien, Juerguista.$B$BQue otros se inspiren en tus ganas de vivir.$B$BAlexstrasza la Protectora" },
		esMX = { subject = "Una y otra vez", text = "Con los tambores de guerra retumbando a lo lejos, es fácil para los habitantes de Azeroth olvidar todo lo que la vida tiene para ofrecer.$B$BTú, por otro lado, has mantenido la dignidad de las buenas razas de Azeroth con tu habilidad para recordar por qué luchamos. No celebrar nuestras victorias es otra forma de derrota. Recuérdalo bien, Juerguista.$B$BQue otros se inspiren en tus ganas de vivir.$B$BAlexstrasza la Protectora" },
		frFR = { subject = "", text = "" },
		zhCN = { subject = "千奇百怪的漫长旅行", text = "随着远方漫天战鼓的响起，对于你们这些艾泽拉斯的外来人来说，忘记生命的意义是一件再正常不过的事情。$B$B你，从另一个角度来说，用你的所作所为来扞卫艾泽拉斯一个高贵种族的尊严，并且去记住我们为之奋斗的东西。 不是为了庆祝我们的胜利，也许是我们在另一个方面的胜利更合适。记住你所做过的事情，旅行者。$B$B希望其他人会为你的行为而欢呼。$B$B阿莱克丝塔萨，生命缚誓者" },
	},
	[2145] = {
		deDE = { subject = "Ein ums andere Mal", text = "Dadurch, dass in der Ferne immer die Kriegstrommeln ertönen, vergessen die Bewohner Azeroths nur allzu leicht all die Dinge, die das Leben zu bieten hat.$B$BIhr habt hingegen mit Eurer Fähigkeit, Euch daran zu erinnern, wofür wir letztlich kämpfen, die Erhabenheit der guten Völker Azeroths bewahrt. Unsere Siege nicht zu feiern wäre eine weitere Form der Niederlage. Denkt immer daran, Feiernder.$B$BMögen andere von Eurem Frohsinn inspiriert werden.$B$BAlextrasza, die Lebensbinderin" },
		esES = { subject = "Una y otra vez", text = "Con los tambores de guerra retumbando a lo lejos, es fácil para los habitantes de Azeroth olvidar todo lo que la vida tiene para ofrecer.$B$BTú, por otro lado, has mantenido la dignidad de las buenas razas de Azeroth con tu habilidad para recordar por qué luchamos. No celebrar nuestras victorias es otra forma de derrota. Recuérdalo bien, Juerguista.$B$BQue otros se inspiren en tus ganas de vivir.$B$BAlexstrasza la Protectora" },
		esMX = { subject = "Una y otra vez", text = "Con los tambores de guerra retumbando a lo lejos, es fácil para los habitantes de Azeroth olvidar todo lo que la vida tiene para ofrecer.$B$BTú, por otro lado, has mantenido la dignidad de las buenas razas de Azeroth con tu habilidad para recordar por qué luchamos. No celebrar nuestras victorias es otra forma de derrota. Recuérdalo bien, Juerguista.$B$BQue otros se inspiren en tus ganas de vivir.$B$BAlexstrasza la Protectora" },
		frFR = { subject = "", text = "" },
		zhCN = { subject = "千奇百怪的漫长旅行", text = "随着远方漫天战鼓的响起，对于你们这些艾泽拉斯的外来人来说，忘记生命的意义是一件再正常不过的事情。$B$B你，从另一个角度来说，用你的所作所为来扞卫艾泽拉斯一个高贵种族的尊严，并且去记住我们为之奋斗的东西。 不是为了庆祝我们的胜利，也许是我们在另一个方面的胜利更合适。记住你所做过的事情，旅行者。$B$B希望其他人会为你的行为而欢呼。$B$B阿莱克丝塔萨，生命缚誓者" },
	},
	[2186] = {
		frFR = { subject = "", text = "" },
	},
	[2187] = {
		frFR = { subject = "", text = "" },
	},
	[2188] = {
		frFR = { subject = "", text = "" },
	},
	[2336] = {
		frFR = { subject = "", text = "" },
	},
	[2516] = {
		deDE = { subject = "Wie man sich Freunde macht", text = "Hallo!$B$BWie ich gehört habe, habt Ihr dem kleinen Stinker ein warmes und liebevolles Zuhause geschaffen... Ich frage mich nun, ob Ihr vielleicht Interesse daran hättet, ein weiteres, eigensinniges Waisenkind aufzunehmen?$B$BDieses kleine Kitz ist zwar ein wenig schüchtern, doch sollte es Euch dank des mitgesandten Gegenstandes ein leichtes sein, seine Freundschaft zu gewinnen: seinem Lieblingsleckstein!$B$B--Breanni" },
		esES = { subject = "Una amiga muy \"salá\"", text = "¡Hola!$B$BTengo entendido que has conseguido un dulce y acogedor hogar incluso para ese travieso de Cuesqui... Tenía la esperanza de que quisieras acoger a otro huérfano inesperado.$B$BEsta Cervatilla es algo tímida, pero no tendrás ningún problema para ganarte su amistad con lo que te envío: ¡Su piedra de sal favorita!$B$B--Breanni" },
		esMX = { subject = "Una amiga muy \"salá\"", text = "¡Hola!$B$BTengo entendido que has conseguido un dulce y acogedor hogar incluso para ese travieso de Cuesqui... Tenía la esperanza de que quisieras acoger a otro huérfano inesperado.$B$BEsta Cervatilla es algo tímida, pero no tendrás ningún problema para ganarte su amistad con lo que te envío: ¡Su piedra de sal favorita!$B$B--Breanni" },
		frFR = { subject = "", text = "" },
		zhCN = { subject = "小宠物猎人", text = "你好！$B$B我知道你已经给了淘气的臭臭一个温暖而又舒适的小窝，我希望你更加乐意收留这只迷你又可爱的小鹿。$B$B这只小鹿很害羞的，但是我想你用这个附赠的小鹿的盐块就能很轻易地和它建立起牢固的友情哦！$B$B--布琳妮" },
	},
	[2536] = {
		deDE = { subject = "Tierisch viele Reittiere", text = "Ich habe gehört, dass Eure Ställe inzwischen fast so groß sind wie meine. Beeindruckend! Vielleicht könnten wir einander aushelfen...$B$BIch habe einen Drachenfalken zuviel und hoffe, dass Ihr ihm ein neues Zuhause geben könnt. Natürlich ist es zum Reittier und nicht zum Jagdtier ausgebildet worden und Ihr werdet sehen, dass es Euch genauso loyal und unermüdlich wie jedes meiner anderen Tiere zur Seite stehen wird.$B$BMit freundlichen Grüßen,$BMei" },
		esES = { subject = "Un montón de monturas", text = "Escuché que tus establos son casi tan extensos como los míos ahora. ¡Impresionante! Quizás podamos ayudarnos tu y yo... Tengo demasiados dracohalcones y esperaba que pudieras darle un hogar a este. Naturalmente, ha sido entrenado como montura y no como mascota de caza, y lo encontrarás tan leal e incansable como cualquier otro corcel que críe.$B$BTuya de nuevo, Mei" },
		esMX = { subject = "Un montón de monturas", text = "Escuché que tus establos son casi tan extensos como los míos ahora. ¡Impresionante! Quizás podamos ayudarnos tu y yo... Tengo demasiados dracohalcones y esperaba que pudieras darle un hogar a este. Naturalmente, ha sido entrenado como montura y no como mascota de caza, y lo encontrarás tan leal e incansable como cualquier otro corcel que críe.$B$BTuya de nuevo, Mei" },
		frFR = { subject = "", text = "" },
		zhCN = { subject = "堆积如山的坐骑", text = "我听说现在你的坐骑数量几乎要和我一样多了，真令人钦佩啊！ 也许你能帮我一件事情，我这里有太多的龙鹰了， 希望你能给它一个家？ 当然，它是被训练成一只合格的坐骑而不是，额，猎人的宠物。你会发现它的优点：不知疲倦，用不完的力气。哈哈。$B$B--梅尔·弗兰希斯" },
	},
	[2537] = {
		deDE = { subject = "Tierisch viele Reittiere", text = "Ich habe gehört, dass Eure Ställe inzwischen fast so groß sind wie meine. Beeindruckend! Vielleicht könnten wir einander aushelfen...$B$BIch habe einen Drachenfalken zuviel und hoffe, dass Ihr ihm ein neues Zuhause geben könnt. Natürlich ist es zum Reittier und nicht zum Jagdtier ausgebildet worden und Ihr werdet sehen, dass es Euch genauso loyal und unermüdlich wie jedes meiner anderen Tiere zur Seite stehen wird.$B$BMit freundlichen Grüßen,$BMei" },
		esES = { subject = "Un montón de monturas", text = "Escuché que tus establos son casi tan extensos como los míos ahora. ¡Impresionante! Quizás podamos ayudarnos tu y yo... Tengo demasiados dracohalcones y esperaba que pudieras darle un hogar a este. Naturalmente, ha sido entrenado como montura y no como mascota de caza, y lo encontrarás tan leal e incansable como cualquier otro corcel que críe.$B$BTuya de nuevo, Mei" },
		esMX = { subject = "Un montón de monturas", text = "Escuché que tus establos son casi tan extensos como los míos ahora. ¡Impresionante! Quizás podamos ayudarnos tu y yo... Tengo demasiados dracohalcones y esperaba que pudieras darle un hogar a este. Naturalmente, ha sido entrenado como montura y no como mascota de caza, y lo encontrarás tan leal e incansable como cualquier otro corcel que críe.$B$BTuya de nuevo, Mei" },
		frFR = { subject = "", text = "" },
		zhCN = { subject = "堆积如山的坐骑", text = "我听说现在你的坐骑数量几乎要和我一样多了，真令人钦佩啊！ 也许你能帮我一件事情，我这里有太多的龙鹰了， 希望你能给它一个家？ 当然，它是被训练成一只合格的坐骑而不是，额，猎人的宠物。你会发现它的优点：不知疲倦，用不完的力气。哈哈。$B$B--梅尔·弗兰希斯" },
	},
	[2760] = {
		frFR = { subject = "", text = "" },
	},
	[2761] = {
		frFR = { subject = "", text = "" },
	},
	[2762] = {
		frFR = { subject = "", text = "" },
	},
	[2763] = {
		frFR = { subject = "", text = "" },
	},
	[2764] = {
		frFR = { subject = "", text = "" },
	},
	[2765] = {
		frFR = { subject = "", text = "" },
	},
	[2766] = {
		frFR = { subject = "", text = "" },
	},
	[2767] = {
		frFR = { subject = "", text = "" },
	},
	[2768] = {
		frFR = { subject = "", text = "" },
	},
	[2769] = {
		frFR = { subject = "", text = "" },
	},
	[2796] = {
		deDE = { subject = "Willkommen im Club Bier des Monats e.V.!", text = "$N,$B$BWillkommen im Club Bier des Monats e.V.! Dieser Club hat es sich zur Aufgabe gemacht Euch einige der besten Biere der Welt anzubieten. $B$BJeden Monat wird Euch ein neues Gebräu zugeschickt. Wenn Euch dieses Gebräu gefällt und Ihr noch mehr davon wollt, sprecht einfach mit den Mitgliedern des Bier des Monats e.V..$B$BNochmals, willkommen im Club, $N.$B$B- Bier des Monats e.V." },
		frFR = { subject = "", text = "" },
		zhCN = { subject = "欢迎来到本月的美酒俱乐部!", text = "$N,$B$B欢迎来到每月美酒俱乐部.$B$B每个月你都会收到我们邮寄给你的美酒. $B$B再次欢迎你的加入, $N.$B$B- 来自每月美酒俱乐部!" },
	},
	[2797] = {
		frFR = { subject = "", text = "" },
	},
	[2798] = {
		frFR = { subject = "", text = "" },
	},
	[2816] = {
		frFR = { subject = "", text = "" },
	},
	[2817] = {
		frFR = { subject = "", text = "" },
	},
	[2903] = {
		frFR = { subject = "", text = "" },
	},
	[2904] = {
		frFR = { subject = "", text = "" },
	},
	[2957] = {
		deDE = { subject = "Ruhm des Schlachtzüglers von Ulduar", text = "$GLieber:Liebe; $N,$B$BIch hoffe, dass es Euch gut geht und dass Ihr Zeit hattet Euch von unseren Mätzchen in Ulduar zu erholen.$B$BMeine Jungs vom Erkundungsteam sind auf dieses arme halbtote Reitdrachen-Jungtier gestoßen. Das muss eine Art Experiment der Eisenzwerge gewesen sein.$B$BWir haben es wieder gesund gemacht und Ihr werdet feststellen, dass es nicht mehr so klein ist! Keiner von uns weiß viel über das Reiten von etwas anderem als Widdern und Maultieren und da wir euch für das was ihr da hinten gemacht habt etwas schuldig sind... Wir dachten Ihr würdet es vielleicht als Geschenk annehmen.$B$BEuer Brann Bronzebart" },
		esES = { subject = "La gloria del asaltante de Ulduar", text = "$gEstimado:Estimada; $n,$B$BEspero que estés bien y que hayas tenido tiempo de recuperarte de nuestras travesuras en Ulduar.$B$BMis muchachos del equipo de prospección se toparon con esta pobre cría de dragón de montar medio muerta. Debe haber sido un experimento de Enano de Hierro de algún tipo.$B$B¡Lo hemos cuidado para que recupere la salud y descubrirás que ya no es tan pequeño! Ninguno de nosotros sabe mucho acerca de montar otra cosa que no sean carneros y mulas de carga, y como te debíamos uno por lo que hiciste allí... Pensamos que quizás lo aceptarías como un regalo.$B$BTuyo,$BBrann Barbabronce" },
		esMX = { subject = "La gloria del asaltante de Ulduar", text = "$gEstimado:Estimada; $n,$B$BEspero que estés bien y que hayas tenido tiempo de recuperarte de nuestras travesuras en Ulduar.$B$BMis muchachos del equipo de prospección se toparon con esta pobre cría de dragón de montar medio muerta. Debe haber sido un experimento de Enano de Hierro de algún tipo.$B$B¡Lo hemos cuidado para que recupere la salud y descubrirás que ya no es tan pequeño! Ninguno de nosotros sabe mucho acerca de montar otra cosa que no sean carneros y mulas de carga, y como te debíamos uno por lo que hiciste allí... Pensamos que quizás lo aceptarías como un regalo.$B$BTuyo,$BBrann Barbabronce" },
		frFR = { subject = "", text = "" },
		zhCN = { subject = "奥杜尔团队高手的荣耀", text = "亲爱的$N，$B$B我希望你能做的不错，然后我们就能夺回对奥杜尔的控制权。$B$B我的那些来自探险者协会的小伙子们决定送你这只铁锈始祖幼龙作为你的奖励。$B$B我想你会很喜欢它吧。你们团队在奥杜尔的征程将铭记史册，继续奋斗吧。$B$B布莱恩·铜须" },
	},
	[2958] = {
		deDE = { subject = "Heroisch: Ruhm des Schlachtzüglers von Ulduar", text = "$GLieber:Liebe; $N,$B$BIch hoffe, dass es Euch gut geht und dass Ihr Zeit hattet Euch von unseren Mätzchen in Ulduar zu erholen.$B$BMeine Jungs vom Erkundungsteam sind auf dieses arme halbtote Reitdrachen-Jungtier gestoßen. Das muss eine Art Experiment der Eisenzwerge gewesen sein.$B$BWir haben es wieder gesund gemacht und Ihr werdet feststellen, dass es nicht mehr so klein ist! Keiner von uns weiß viel über das Reiten von etwas anderem als Widdern und Maultieren und da wir euch für das was ihr da hinten gemacht habt etwas schuldig sind... Wir dachten Ihr würdet es vielleicht als Geschenk annehmen.$B$BEuer Brann Bronzebart" },
		esES = { subject = "La gloria del asaltante de Ulduar", text = "$gEstimado:Estimada; $n,$B$BEspero que estés bien y que hayas tenido tiempo de recuperarte de nuestras travesuras en Ulduar.$B$BMis muchachos del equipo de prospección se toparon con esta pobre cría de dragón de montar medio muerta. Debe haber sido un experimento de Enano de Hierro de algún tipo.$B$B¡Lo hemos cuidado para que recupere la salud y descubrirás que ya no es tan pequeño! Ninguno de nosotros sabe mucho acerca de montar otra cosa que no sean carneros y mulas de carga, y como te debíamos uno por lo que hiciste allí... Pensamos que quizás lo aceptarías como un regalo.$B$BTuyo,$BBrann Barbabronce" },
		esMX = { subject = "La gloria del asaltante de Ulduar", text = "$gEstimado:Estimada; $n,$B$BEspero que estés bien y que hayas tenido tiempo de recuperarte de nuestras travesuras en Ulduar.$B$BMis muchachos del equipo de prospección se toparon con esta pobre cría de dragón de montar medio muerta. Debe haber sido un experimento de Enano de Hierro de algún tipo.$B$B¡Lo hemos cuidado para que recupere la salud y descubrirás que ya no es tan pequeño! Ninguno de nosotros sabe mucho acerca de montar otra cosa que no sean carneros y mulas de carga, y como te debíamos uno por lo que hiciste allí... Pensamos que quizás lo aceptarías como un regalo.$B$BTuyo,$BBrann Barbabronce" },
		frFR = { subject = "", text = "" },
		zhCN = { subject = "英雄：奥杜尔团队高手的荣耀", text = "亲爱的$N，$B$B我希望你能做的不错，然后我们就能夺回对奥杜尔的控制权。$B$B我的那些来自探险者协会的小伙子们决定送你这只铁缚始祖幼龙作为你的奖励。$B$B我想你会很喜欢它吧。你们团队在奥杜尔的征程将铭记史册，继续奋斗吧。$B$B布莱恩·铜须" },
	},
	[3036] = {
		frFR = { subject = "", text = "" },
	},
	[3037] = {
		frFR = { subject = "", text = "" },
	},
	[3117] = {
		frFR = { subject = "", text = "" },
	},
	[3259] = {
		frFR = { subject = "", text = "" },
	},
	[3316] = {
		frFR = { subject = "", text = "" },
	},
	[3478] = {
		deDE = { subject = "Der vergessene Puter", text = "Könnt Ihr begreifen, wie es dieser fette Truthahn es lebendig durch den November geschaft hat?!$B$BAlle seine Freunde sind auf den reich gedeckten Tischen serviert worden. Mit Moosbeerenchutney und Gewürzbrotfüllung und... OOOH... jetzt bekomme ich Hunger. Egal! Er ist jetzt ganz allein. Deswegen habe ich überlegt, ob Ihr Euch vielleicht um Ihn kümmern würdet. In meinem Laden ist einfach nicht mehr genug Platz für ihn!$B$BHaltet ihn nur bitte von Kochstellen fern. Er bekommt in ihrer Nähe immer so einen merkwürdigen Blick...$B$B--Breanni" },
		esES = { subject = "Un pavo aún no engullido", text = "¿Puedes creer que este pavo regordete sobrevivió a noviembre?$B$BDado que todos sus amigos se han servido en abundantes mesas con salsa de arándanos y rellenos de pan con especias y... ooo... tengo hambre. ¡Pero de todos modos! Ahora está solo, así que esperaba que estuvieras dispuesto a cuidar de él. ¡Simplemente no queda suficiente espacio en mi tienda!$B$BMantenlo alejado de los fogones de cocina, por favor. Tiene esta extraña mirada en sus ojos alrededor de los fogones..." },
		esMX = { subject = "Un pavo aún no engullido", text = "¿Puedes creer que este pavo regordete sobrevivió a noviembre?$B$BDado que todos sus amigos se han servido en abundantes mesas con salsa de arándanos y rellenos de pan con especias y... ooo... tengo hambre. ¡Pero de todos modos! Ahora está solo, así que esperaba que estuvieras dispuesto a cuidar de él. ¡Simplemente no queda suficiente espacio en mi tienda!$B$BMantenlo alejado de los fogones de cocina, por favor. Tiene esta extraña mirada en sus ojos alrededor de los fogones..." },
		frFR = { subject = "", text = "" },
		zhCN = { subject = "不会咕咕的火鸡！", text = "你能相信是这只滚圆的火鸡让整个十一月都洋溢着节日的气氛吗？$B$B然后好多朋友聚集在丰盛的饭桌前，上面放满了蔓越橘果酱、一片片切好的面包以及…哦哦哦…我感觉到自己都要流口水了！但是，它依然是孤零零的一只，所以我希望你能好好地照顾它，给它温暖—别吃掉它！虽然它也不会占多少地方，可是我店里早就已经拥挤不堪啦！$B$B嗯，记得让它远离烹饪用火，因为那些小火在它眼里是一种特殊的存在…" },
	},
	[3656] = {
		deDE = { subject = "Der vergessene Puter", text = "Könnt Ihr begreifen, wie es dieser fette Truthahn es lebendig durch den November geschaft hat?!$B$BAlle seine Freunde sind auf den reich gedeckten Tischen serviert worden. Mit Moosbeerenchutney und Gewürzbrotfüllung und... OOOH... jetzt bekomme ich Hunger. Egal! Er ist jetzt ganz allein. Deswegen habe ich überlegt, ob Ihr Euch vielleicht um Ihn kümmern würdet. In meinem Laden ist einfach nicht mehr genug Platz für ihn!$B$BHaltet ihn nur bitte von Kochstellen fern. Er bekommt in ihrer Nähe immer so einen merkwürdigen Blick...$B$B--Breanni" },
		esES = { subject = "Un pavo aún no engullido", text = "¿Puedes creer que este pavo regordete sobrevivió a noviembre?$B$BDado que todos sus amigos se han servido en abundantes mesas con salsa de arándanos y rellenos de pan con especias y... ooo... tengo hambre. ¡Pero de todos modos! Ahora está solo, así que esperaba que estuvieras dispuesto a cuidar de él. ¡Simplemente no queda suficiente espacio en mi tienda!$B$BMantenlo alejado de los fogones de cocina, por favor. Tiene esta extraña mirada en sus ojos alrededor de los fogones..." },
		esMX = { subject = "Un pavo aún no engullido", text = "¿Puedes creer que este pavo regordete sobrevivió a noviembre?$B$BDado que todos sus amigos se han servido en abundantes mesas con salsa de arándanos y rellenos de pan con especias y... ooo... tengo hambre. ¡Pero de todos modos! Ahora está solo, así que esperaba que estuvieras dispuesto a cuidar de él. ¡Simplemente no queda suficiente espacio en mi tienda!$B$BMantenlo alejado de los fogones de cocina, por favor. Tiene esta extraña mirada en sus ojos alrededor de los fogones..." },
		frFR = { subject = "", text = "" },
		zhCN = { subject = "不会咕咕的火鸡！", text = "你能相信是这只滚圆的火鸡让整个十一月都洋溢着节日的气氛吗？$B$B然后好多朋友聚集在丰盛的饭桌前，上面放满了蔓越橘果酱、一片片切好的面包以及…哦哦哦…我感觉到自己都要流口水了！但是，它依然是孤零零的一只，所以我希望你能好好地照顾它，给它温暖—别吃掉它！虽然它也不会占多少地方，可是我店里早就已经拥挤不堪啦！$B$B嗯，记得让它远离烹饪用火，因为那些小火在它眼里是一种特殊的存在…" },
	},
	[3857] = {
		deDE = { subject = "Meister der Insel der Eroberung", text = "$GEhrenvoller:Ehrenvolle; $N,$B$BFür Eure Taten auf der Insel der Eroberung ist es mir eine Ehre Euch diesen Wappenrock zu überreichen. Tragt ihn mit Stolz.$B$BHochkommandant Halford Wyrmbann, 7. Legion" },
		esES = { subject = "$gMaestro:Maestra; de la Isla de la Conquista", text = "Honorable $N,$B$BPor tus hazañas en la Isla de la Conquista, es un honor para mí presentarte este tabardo. Úselo con orgullo.$B$BAlto Comandante, Séptima Legión" },
		esMX = { subject = "$gMaestro:Maestra; de la Isla de la Conquista", text = "Honorable $N,$B$BPor tus hazañas en la Isla de la Conquista, es un honor para mí presentarte este tabardo. Úselo con orgullo.$B$BAlto Comandante, Séptima Legión" },
		frFR = { subject = "Maître de l'île des Conquérants", text = "" },
		zhCN = { subject = "征服之岛的主人", text = "荣耀属于你，$N，$B$B你在征服之岛的英雄表现，为我们军团做出了卓越的贡献，为此，送你这件战袍以示感谢。$B$B第七军团高阶指挥官" },
	},
	[3957] = {
		deDE = { subject = "Meister der Insel der Eroberung", text = "$GEhrenvoller:Ehrenvolle; $N,$B$BFür Eure Taten auf der Insel der Eroberung ist es mir eine Ehre Euch diesen Wappenrock zu überreichen. Tragt ihn mit Stolz.$B$BOberanführer Agmar" },
		esES = { subject = "$gMaestro:Maestra; de la Isla de la Conquista", text = "Honorable $N,$B$BPor tus hazañas en la Isla de la Conquista, es un honor para mí presentarte este tabardo. Úselo con orgullo.$B$BAlto Comandante, Séptima Legión" },
		esMX = { subject = "$gMaestro:Maestra; de la Isla de la Conquista", text = "Honorable $N,$B$BPor tus hazañas en la Isla de la Conquista, es un honor para mí presentarte este tabardo. Úselo con orgullo.$B$BAlto Comandante, Séptima Legión" },
		frFR = { subject = "Maître de l'île des Conquérants", text = "" },
		zhCN = { subject = "征服之岛的主人", text = "尊敬的$N,$B$B在征服之岛的战场上，你英勇杀敌，功绩卓着，给你送上这件战袍是我的荣耀。$B$B奥格瑞玛大领主" },
	},
	[4078] = {
		frFR = { subject = "", text = "" },
	},
	[4079] = {
		deDE = { subject = "Ein Tribut an die Unsterblichkeit", text = "$GLieber:Liebe; $N,$B$BGeschichten über Eure jüngste Leistung in der Prüfung des obersten Kreuzfahrers werden noch lange Zeit erzählt und nacherzählt werden. Als der Argentumkreuzzug die größten Meister von Azeroth aufrief ihren Kampfgeist im Schmelztiegel des Kolosseums zu erproben, hoffte ich wider Erwarten, dass Leuchtfeuer wie Ihr und Eure Gefährten aus dem Kampf hervorgehen würden.$B$BWir werden Euch in der kommenden Schlacht gegen den Lichkönig dringend brauchen. Aber an diesem Tag solltet Ihr Euch freuen und Eure ruhmreiche Leistung feiern und dieses Geschenk eines unserer besten Schlachtrösser annehmen. Wenn die Geißel ihr Banner am Horizont auftauchen sieht, Held, wird ihr Ende nahe sein!$B$BMit freundlichen Grüßen,$BTirion Fordring" },
		esES = { subject = "Un tributo a la inmortalidad", text = "Estimado $n,$B$BLos relatos de su actuación reciente en la Prueba del Gran Cruzado se contarán y volverán a contar durante siglos. Mientras la Cruzada Argenta hizo un llamado a los más grandes campeones de Azeroth para que pusieran a prueba su temple en el crisol del Coliseo, esperaba contra toda esperanza que los faros de luz como tú y tus compañeros pudieran emerger de la refriega.$B$BTe necesitaremos desesperadamente en la próxima batalla contra el Rey Exánime. Pero en este día, regocíjate y celebra tu glorioso logro y acepta este regalo; uno de nuestros mejores caballos de guerra. ¡Cuando la Plaga vea su estandarte asomándose en el horizonte, $ghéroe:heroína;, su fin estará cerca!$B$BTuyo con honor,$BTirion Vadin" },
		esMX = { subject = "Un tributo a la inmortalidad", text = "Estimado $n,$B$BLos relatos de su actuación reciente en la Prueba del Gran Cruzado se contarán y volverán a contar durante siglos. Mientras la Cruzada Argenta hizo un llamado a los más grandes campeones de Azeroth para que pusieran a prueba su temple en el crisol del Coliseo, esperaba contra toda esperanza que los faros de luz como tú y tus compañeros pudieran emerger de la refriega.$B$BTe necesitaremos desesperadamente en la próxima batalla contra el Rey Exánime. Pero en este día, regocíjate y celebra tu glorioso logro y acepta este regalo; uno de nuestros mejores caballos de guerra. ¡Cuando la Plaga vea su estandarte asomándose en el horizonte, $ghéroe:heroína;, su fin estará cerca!$B$BTuyo con honor,$BTirion Vadin" },
		frFR = { subject = "Une offrande à l'immortalité", text = "" },
		zhCN = { subject = "对不朽的嘉奖", text = "亲爱的$N，$B$B你在大十字军竞技场的事迹这么久以来被反复传颂。大十字军竞技场是为了选拔以后进军冰冠城塞的勇士而设立的一座竞技场，我希望有越来越多的勇士能在这座竞技场里脱颖而出，然后直捣冰冠城塞。很显然，你们引起了我的注意。$B$B我们需要你们的力量来对抗巫妖王。不过这么些天来，你们一直在举办庆祝活动，我也不好意思打扰你们，现在把这匹最好的战马送给你，当天灾军团看到竖立在它后边的银白十字军战旗时，那胆战心惊的模样想必你也很乐意看到吧？$B$B荣耀伴随着你$B提里奥·弗丁" },
	},
	[4080] = {
		frFR = { subject = "", text = "" },
	},
	[4156] = {
		deDE = { subject = "Ein Tribut an die Unsterblichkeit", text = "$GLieber:Liebe; $N,$B$BGeschichten über Eure jüngste Leistung in der Prüfung des obersten Kreuzfahrers werden noch lange Zeit erzählt und nacherzählt werden. Als der Argentumkreuzzug die größten Meister von Azeroth aufrief ihren Kampfgeist im Schmelztiegel des Kolosseums zu erproben, hoffte ich wider Erwarten, dass Leuchtfeuer wie Ihr und Eure Gefährten aus dem Kampf hervorgehen würden.$B$BWir werden Euch in der kommenden Schlacht gegen den Lichkönig dringend brauchen. Aber an diesem Tag solltet Ihr Euch freuen und Eure ruhmreiche Leistung feiern und dieses Geschenk eines unserer besten Schlachtrösser annehmen. Wenn die Geißel ihr Banner am Horizont auftauchen sieht, Held, wird ihr Ende nahe sein!$B$BMit freundlichen Grüßen,$BTirion Fordring" },
		esES = { subject = "Un tributo a la inmortalidad", text = "Estimado $n,$B$BLos relatos de su actuación reciente en la Prueba del Gran Cruzado se contarán y volverán a contar durante siglos. Mientras la Cruzada Argenta hizo un llamado a los más grandes campeones de Azeroth para que pusieran a prueba su temple en el crisol del Coliseo, esperaba contra toda esperanza que los faros de luz como tú y tus compañeros pudieran emerger de la refriega.$B$BTe necesitaremos desesperadamente en la próxima batalla contra el Rey Exánime. Pero en este día, regocíjate y celebra tu glorioso logro y acepta este regalo; uno de nuestros mejores caballos de guerra. ¡Cuando la Plaga vea su estandarte asomándose en el horizonte, $ghéroe:heroína;, su fin estará cerca!$B$BTuyo con honor,$BTirion Vadin" },
		esMX = { subject = "Un tributo a la inmortalidad", text = "Estimado $n,$B$BLos relatos de su actuación reciente en la Prueba del Gran Cruzado se contarán y volverán a contar durante siglos. Mientras la Cruzada Argenta hizo un llamado a los más grandes campeones de Azeroth para que pusieran a prueba su temple en el crisol del Coliseo, esperaba contra toda esperanza que los faros de luz como tú y tus compañeros pudieran emerger de la refriega.$B$BTe necesitaremos desesperadamente en la próxima batalla contra el Rey Exánime. Pero en este día, regocíjate y celebra tu glorioso logro y acepta este regalo; uno de nuestros mejores caballos de guerra. ¡Cuando la Plaga vea su estandarte asomándose en el horizonte, $ghéroe:heroína;, su fin estará cerca!$B$BTuyo con honor,$BTirion Vadin" },
		frFR = { subject = "Une offrande à l'immortalité", text = "" },
		zhCN = { subject = "对不朽的嘉奖", text = "亲爱的$N，$B$B你在大十字军竞技场的事迹这么久以来被反复传颂。大十字军竞技场是为了选拔以后进军冰冠城塞的勇士而设立的一座竞技场，我希望有越来越多的勇士能在这座竞技场里脱颖而出，然后直捣冰冠城塞。很显然，你们引起了我的注意。$B$B我们需要你们的力量来对抗巫妖王。不过这么些天来，你们一直在举办庆祝活动，我也不好意思打扰你们，现在把这匹最好的战马送给你，当天灾军团看到竖立在它后边的银白十字军战旗时，那胆战心惊的模样想必你也很乐意看到吧？$B$B荣耀伴随着你$B提里奥·弗丁" },
	},
	[4477] = {
		frFR = { subject = "", text = "" },
	},
	[4478] = {
		deDE = { subject = "Streuner", text = "Werter Meister der Geduld, wir möchten Eure Beharrlichkeit belohnen, mit der Ihr immer wieder Dungeons mit Leuten betretet, die Ihr wahrscheinlich noch nie zuvor getroffen habt. Hoffentlich habt Ihr ein paar Jungspunden zeigen können, wie der Hase läuft.$B$BLange Rede, kurzer Sinn. Wir haben zufällig gehört, dass Ihr mit Zufallsgruppen herumstreunt. Und wie der Zufall so will ist hier also ein kleiner Streuner, den wir Euch zufallen lassen, um mit Euch zu streunen, während Ihr zufälligen Zufällen zufallt, oder so.$B$BKnuddels.$B$BDas Entwickler-Team von WoW" },
		esES = { subject = "P.U.G.", text = "Estimado individuo muy paciente,$B$BNos gustaría reconocer su tenacidad en la gestión de mazmorras con personas que probablemente no haya conocido antes. Con suerte, incluso les enseñaste a algunos novatos las cuerdas en tus grupos de recogida.$B$BEn resumen, escuchamos que te gustan los pugs. Así que aquí tienes un pug para tu pug, para que puedas pug mientras pug. O algo.$B$BAbrazos,$B$BTus amigos del equipo de desarrollo de WoW." },
		esMX = { subject = "P.U.G.", text = "Estimado individuo muy paciente,$B$BNos gustaría reconocer su tenacidad en la gestión de mazmorras con personas que probablemente no haya conocido antes. Con suerte, incluso les enseñaste a algunos novatos las cuerdas en tus grupos de recogida.$B$BEn resumen, escuchamos que te gustan los pugs. Así que aquí tienes un pug para tu pug, para que puedas pug mientras pug. O algo.$B$BAbrazos,$B$BTus amigos del equipo de desarrollo de WoW." },
		frFR = { subject = "Groupe improvisé", text = "$gCher membre assidu:Chère membre assidue;,\n\nnous aimerions récompenser votre ténacité à parcourir les donjons avec des personnes que vous n'aviez probablement jamais rencontrées auparavant. Vous avez peut-être même appris les ficelles du métier à quelques petits nouveaux.\n\nBref, nous avons entendu dire que vous aimiez les groupes improvisés. Alors voici le petit Groopy, qui proclamera à tout le monde : « Vous savez quoi ? J'suis groupé ! »\n\nAvec toute notre affection,\n\nVos amis de l'équipe de développement de WoW" },
		zhCN = { subject = "活泼的地雷犬", text = "非常有耐心的冒险者，$B$B你在地城中和或许以前连面都没见过的伙伴一同战斗的事情我们已经知道了，我们很高兴还有你这样的人存在，希望你能在以后的地城旅行中能和伙伴们处理好关系，一定要和谐哦。$B$B长话短说吧，为了奖励你在地城中的行为，无论你以前在地城中什么样，希望你在以后能认真对待每一个副本和朋友。嗯，先送你一只地雷犬吧，它是一个很活泼的狗狗。$B$B拥抱你$B$B你在魔兽世界开发组里的朋友" },
	},
	[4530] = {
		frFR = { subject = "", text = "" },
		zhCN = { subject = "冰封王座（10人）", text = "勇士们,你们在冰封王座上摧毁了巫妖王，黯刃骑士团佩服你们，这是我们给你的礼物!" },
	},
	[4583] = {
		frFR = { subject = "", text = "" },
		zhCN = { subject = "冰河踏破者", text = "勇士们,你们在冰封王座上摧毁了巫妖王，黯刃骑士团佩服你们，这是我们给你的礼物!" },
	},
	[4584] = {
		frFR = { subject = "", text = "" },
		zhCN = { subject = "黎明之光", text = "勇士们,你们在冰封王座上摧毁了巫妖王，黯刃骑士团佩服你们，这是我们给你的礼物!" },
	},
	[4597] = {
		frFR = { subject = "", text = "" },
		zhCN = { subject = "冰封王座（25人）", text = "勇士们,你们在冰封王座上摧毁了巫妖王，黯刃骑士团佩服你们，这是我们给你的礼物!" },
	},
	[4598] = {
		frFR = { subject = "", text = "" },
	},
	[4602] = {
		deDE = { subject = "Ruhm des Schlachtzüglers von Eiskrone", text = "$N,$B$BAls der Einfluss des Lichkönigs schwand, haben sich einige seiner mächtigeren Schergen aus seinem Griff befreit.$B$BDieser von meinen Männern gefangen genommene Frostwyrm Drache ist ein Paradebeispiel dafür. Sie hat einen eigenen Willen und noch mehr.$B$BEiner meiner Männer verlor einen Arm als er sie einritt, aber sie kann jetzt recht gut mit Reitern umgehen - vorausgesetzt Ihr seid geschickt und habt einen starken Willen.$B$BBitte nehmt diese prächtige Bestie als Geschenk der Ritter der Schwarzen Klinge an. Es war mir eine Ehre, an Eurer Seite in der größten aller Schlachten zu kämpfen.$B$BHochachtungsvoll,$BDarion Mograine." },
		esES = { subject = "La gloria del asaltante de Corona de Hielo", text = "$n,$B$BA medida que la influencia del Rey Exánime se desvanece, algunos de sus secuaces más poderosos se han liberado de sus manos.$B$BEste dragón vermis de hielo que mis hombres capturaron es un excelente ejemplo. Ella tiene voluntad propia y algo más.$B$BUno de mis hombres perdió un brazo al domarla, pero ahora se adapta bastante bien a los jinetes, siempre que ellos mismos sean hábiles y de voluntad fuerte.$B$BAcepta esta magnífica bestia como regalo de los Caballeros de la Espada de Ébano. Fue un honor luchar a tu lado en esta gran batalla.$B$BCon honor,$BDarion Mograine." },
		esMX = { subject = "La gloria del asaltante de Corona de Hielo", text = "$n,$B$BA medida que la influencia del Rey Exánime se desvanece, algunos de sus secuaces más poderosos se han liberado de sus manos.$B$BEste dragón vermis de hielo que mis hombres capturaron es un excelente ejemplo. Ella tiene voluntad propia y algo más.$B$BUno de mis hombres perdió un brazo al domarla, pero ahora se adapta bastante bien a los jinetes, siempre que ellos mismos sean hábiles y de voluntad fuerte.$B$BAcepta esta magnífica bestia como regalo de los Caballeros de la Espada de Ébano. Fue un honor luchar a tu lado en esta gran batalla.$B$BCon honor,$BDarion Mograine." },
		frFR = { subject = "", text = "" },
		zhCN = { subject = "冰河踏破者的荣耀（10人）", text = "$N,$B$B当巫妖王的影响力日渐薄弱的时候，有不少昔日在他麾下很强力的人脱离了他的控制。$B$B这只被我们捕获的冰霜巨龙就是一个很好的例子。它有强烈的自主意识，并且我们还有更多的这种巨龙。$B$B我们当中的一个人虽然在一次战斗中光荣地失去了一只胳膊，不过依然能很好的驾驭它。—很明显，它被驯服的很好，并且给了他们自信。$B$B请接受这只来自黑锋骑士团的礼物，在这场伟大的战斗中有你们陪同，真的很荣幸。$B$B荣誉属于你们。$B达利安·莫格莱尼" },
	},
	[4603] = {
		deDE = { subject = "Ruhm des Schlachtzüglers von Eiskrone", text = "$N,$B$BAls der Einfluss des Lichkönigs schwand, haben sich einige seiner mächtigeren Schergen aus seinem Griff befreit.$B$BDieser von meinen Männern gefangen genommene Frostwyrm Drache ist ein Paradebeispiel dafür. Sie hat einen eigenen Willen und noch mehr.$B$BEiner meiner Männer verlor einen Arm als er sie einritt, aber sie kann jetzt recht gut mit Reitern umgehen - vorausgesetzt Ihr seid geschickt und habt einen starken Willen.$B$BBitte nehmt diese prächtige Bestie als Geschenk der Ritter der Schwarzen Klinge an. Es war mir eine Ehre, an Eurer Seite in der größten aller Schlachten zu kämpfen.$B$BHochachtungsvoll,$BDarion Mograine." },
		esES = { subject = "La gloria del asaltante de Corona de Hielo", text = "$n,$B$BA medida que la influencia del Rey Exánime se desvanece, algunos de sus secuaces más poderosos se han liberado de sus manos.$B$BEste dragón vermis de hielo que mis hombres capturaron es un excelente ejemplo. Ella tiene voluntad propia y algo más.$B$BUno de mis hombres perdió un brazo al domarla, pero ahora se adapta bastante bien a los jinetes, siempre que ellos mismos sean hábiles y de voluntad fuerte.$B$BAcepta esta magnífica bestia como regalo de los Caballeros de la Espada de Ébano. Fue un honor luchar a tu lado en esta gran batalla.$B$BCon honor,$BDarion Mograine." },
		esMX = { subject = "La gloria del asaltante de Corona de Hielo", text = "$n,$B$BA medida que la influencia del Rey Exánime se desvanece, algunos de sus secuaces más poderosos se han liberado de sus manos.$B$BEste dragón vermis de hielo que mis hombres capturaron es un excelente ejemplo. Ella tiene voluntad propia y algo más.$B$BUno de mis hombres perdió un brazo al domarla, pero ahora se adapta bastante bien a los jinetes, siempre que ellos mismos sean hábiles y de voluntad fuerte.$B$BAcepta esta magnífica bestia como regalo de los Caballeros de la Espada de Ébano. Fue un honor luchar a tu lado en esta gran batalla.$B$BCon honor,$BDarion Mograine." },
		frFR = { subject = "Gloire à l'écumeur de raids de la Couronne de glace", text = "" },
		zhCN = { subject = "冰河踏破者的荣耀（25人）", text = "$N,$B$B当巫妖王的影响力日渐薄弱的时候，有不少昔日在他麾下很强力的人脱离了他的控制。$B$B这只被我们捕获的冰霜巨龙就是一个很好的例子。它有强烈的自主意识，并且我们还有更多的这种巨龙。$B$B我们当中的一个人虽然在一次战斗中光荣地失去了一只胳膊，不过依然能很好的驾驭它。—很明显，它被驯服的很好，并且给了他们自信。$B$B请接受这只来自黑锋骑士团的礼物，在这场伟大的战斗中有你们陪同，真的很荣幸。$B$B荣誉属于你们。$B达利安·莫格莱尼" },
	},
	[4784] = {
		deDE = { subject = "Emblem Rüstmeister in Dalaran's Silbernen Enklave", text = "Eure Erfolge in Nordend sind nicht unbemerkt geblieben, Freund.$B$BDie verdienten Embleme können benutzt werden, um Gegenstände bei den verschiedenen Rüstmeistern für Embleme zu kaufen.$B$BIhr findet uns in der Silbernen Enklave, wo jede Emblemart einen eigenen Rüstmeister hat.$B$BWir freuen uns auf Eure Ankunft!" },
		esES = { subject = "Intendente de emblemas en el Enclave de Plata de Dalaran", text = "Tus logros en Rasganorte no han pasado desapercibidos, amigo.$B$BLos emblemas que hayas ganado se pueden usar para comprar equipo de los distintos Intendente de emblemas en Dalaran.$B$BPuede encontrarnos en el Enclave de Plata, donde cada variedad de emblema tiene su propio intendente.$B$B¡Esperamos tu llegada!" },
		esMX = { subject = "Intendente de emblemas en el Enclave de Plata de Dalaran", text = "Tus logros en Rasganorte no han pasado desapercibidos, amigo.$B$BLos emblemas que hayas ganado se pueden usar para comprar equipo de los distintos Intendente de emblemas en Dalaran.$B$BPuede encontrarnos en el Enclave de Plata, donde cada variedad de emblema tiene su propio intendente.$B$B¡Esperamos tu llegada!" },
		frFR = { subject = "", text = "" },
		zhCN = { subject = "银色盟约的纹章收集者", text = "朋友，你在诺森德所取得的成就令人不得不注目。$B$B你所获取的每枚纹章都能在达拉然兑换到各种强力的装备，然后武装自己，不是件很快乐的事么？$B$B我们就在达拉然的银色盟约，在那儿，每种纹章都有对应的兑换师，来看看吧。$B$B我们期待你的到来！" },
	},
	[4785] = {
		deDE = { subject = "Emblem Rüstmeister in Dalaran's Sonnenhäschers Zuflucht", text = "Eure Erfolge in Nordend sind nicht unbemerkt geblieben, Freund.$B$BDie verdienten Embleme können benutzt werden, um Gegenstände bei den verschiedenen Rüstmeistern für Embleme zu kaufen.$B$BIhr findet uns in Sonnenhäschers Zuflucht, wo jede Emblemart einen eigenen Rüstmeister hat.$B$BWir freuen uns auf Eure Ankunft!" },
		esES = { subject = "Intendente de emblemas en el Santuario Atracasol de Dalaran", text = "Tus logros en Rasganorte no han pasado desapercibidos, amigo.$B$BLos emblemas que hayas ganado se pueden usar para comprar equipo de los distintos Intendente de emblemas en Dalaran.$B$BPuede encontrarnos en el Santuario Atracasol, donde cada variedad de emblema tiene su propio intendente.$B$B¡Esperamos tu llegada!" },
		esMX = { subject = "Intendente de emblemas en el Santuario Atracasol de Dalaran", text = "Tus logros en Rasganorte no han pasado desapercibidos, amigo.$B$BLos emblemas que hayas ganado se pueden usar para comprar equipo de los distintos Intendente de emblemas en Dalaran.$B$BPuede encontrarnos en el Santuario Atracasol, donde cada variedad de emblema tiene su propio intendente.$B$B¡Esperamos tu llegada!" },
		frFR = { subject = "", text = "" },
		zhCN = { subject = "达拉然夺日者圣堂的纹章收集者", text = "朋友，你在诺森德所取得的成就让人不得不注意。$B$B你所获取的每枚纹章都能在达拉然换取对应的装备，武装自己来更强大，不是每个人都乐意的么？$B$B在达拉然的夺日者圣堂，你能找到每一种纹章所对应的兑换师，在他的身上，你能收获许多。$B$B期待你的到来！" },
	},
}
