"""
Exports the achievement-related tables from the mangos world database into
static Lua data files consumed by the Achiever addon.

Usage:
    python export_static_achievement_data.py

Regenerate this data any time the mangos database's achievement tables
change (e.g. after a DBC re-import). The output files are plain generated
data -- do not hand-edit them, edit this script and re-run it instead.
"""

import os
import pymysql

DB_HOST = "localhost"
DB_USER = "mangos"
DB_PASSWORD = "mangos"
DB_NAME = "mangos"

OUTPUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "Data")

HEADER = (
	"-- AUTO-GENERATED by tools/export_static_achievement_data.py -- do not hand-edit.\n"
	"-- Source: mangos.{table} ({count} rows)\n\n"
)


def lua_string(value):
	"""Escapes a Python string (or None) into a double-quoted Lua string literal."""
	if value is None:
		return '""'
	value = str(value)
	value = value.replace("\\", "\\\\")
	value = value.replace('"', '\\"')
	value = value.replace("\r\n", "\n")
	value = value.replace("\n", "\\n")
	value = value.replace("\t", "\\t")
	return '"' + value + '"'


def lua_number(value):
	return str(int(value)) if value is not None else "0"


def connect():
	return pymysql.connect(host=DB_HOST, user=DB_USER, password=DB_PASSWORD, database=DB_NAME, charset="utf8")


def get_excluded_categories(cur):
	"""Returns the set of achievement_category_dbc IDs that are patch 255
	(post-Classic content, e.g. TBC/WotLK) or descend from a category that is."""
	cur.execute("SELECT ID, Parent, patch FROM achievement_category_dbc")
	parent_of = {}
	patch_of = {}
	for id_, parent, patch in cur.fetchall():
		parent_of[id_] = parent
		patch_of[id_] = patch

	excluded = {}

	def is_excluded(category_id, seen):
		if category_id in excluded:
			return excluded[category_id]
		if category_id in seen:
			return False  # cycle guard; shouldn't happen in practice

		seen.add(category_id)
		result = patch_of.get(category_id) == 255
		if not result:
			parent = parent_of.get(category_id, -1)
			if parent != -1 and parent in patch_of:
				result = is_excluded(parent, seen)

		excluded[category_id] = result
		return result

	for category_id in patch_of:
		is_excluded(category_id, set())

	return set(cid for cid, is_excl in excluded.items() if is_excl)


def write_file(filename, table, count, body_lines):
	path = f"{OUTPUT_DIR}/{filename}"
	with open(path, "w", encoding="utf-8") as f:
		f.write(HEADER.format(table=table, count=count))
		f.write("AchieverStaticData = AchieverStaticData or {}\n\n")
		for line in body_lines:
			f.write(line + "\n")
	print(f"wrote {path} ({count} rows)")


def export_categories(cur, excluded_categories):
	cur.execute("SELECT ID, Parent, Name_Lang_enUS, Ui_Order, patch FROM achievement_category_dbc ORDER BY ID")
	all_rows = cur.fetchall()
	rows = [row for row in all_rows if row[0] not in excluded_categories]
	print(f"achievement_category_dbc: skipping {len(all_rows) - len(rows)} post-Classic categories")

	lines = ["AchieverStaticData.categories = {"]
	for id_, parent, name, ui_order, patch in rows:
		lines.append(
			f"\t[{id_}] = {{ parent = {lua_number(parent)}, name = {lua_string(name)}, "
			f"uiOrder = {lua_number(ui_order)}, patch = {lua_number(patch)} }},"
		)
	lines.append("}")
	write_file("Categories.lua", "achievement_category_dbc", len(rows), lines)


def export_achievements(cur, excluded_categories):
	cur.execute(
		"SELECT ID, Faction, Instance_Id, Supercedes, Title_Lang_enUS, Description_Lang_enUS, "
		"Category, Points, Ui_Order, Flags, IconID, Reward_Lang_enUS, Minimum_Criteria, "
		"Shares_Criteria, patch FROM achievement_dbc ORDER BY ID"
	)
	all_rows = cur.fetchall()
	# Patch-based filtering disabled for now -- export everything regardless of patch.
	rows = [
		row for row in all_rows
		if row[6] not in excluded_categories
	]
	print(f"achievement_dbc: skipping {len(all_rows) - len(rows)} excluded-category achievements")

	lines = ["AchieverStaticData.achievements = {"]
	for (id_, faction, instance_id, supercedes, title, description, category, points,
			ui_order, flags, icon_id, reward, min_criteria, shares_criteria, patch) in rows:
		lines.append(
			f"\t[{id_}] = {{\n"
			f"\t\tfaction = {lua_number(faction)}, instanceId = {lua_number(instance_id)}, "
			f"supercedes = {lua_number(supercedes)},\n"
			f"\t\ttitle = {lua_string(title)},\n"
			f"\t\tdescription = {lua_string(description)},\n"
			f"\t\tcategory = {lua_number(category)}, points = {lua_number(points)}, "
			f"uiOrder = {lua_number(ui_order)}, flags = {lua_number(flags)}, iconId = {lua_number(icon_id)},\n"
			f"\t\treward = {lua_string(reward)},\n"
			f"\t\tminimumCriteria = {lua_number(min_criteria)}, sharesCriteria = {lua_number(shares_criteria)}, "
			f"patch = {lua_number(patch)}\n"
			f"\t}},"
		)
	lines.append("}")
	write_file("Achievements.lua", "achievement_dbc", len(rows), lines)


def export_criteria(cur):
	cur.execute(
		"SELECT ID, Achievement_Id, Type, Asset_Id, Quantity, Start_Event, Start_Asset, "
		"Fail_Event, Fail_Asset, Description_Lang_enUS, Flags, Timer_Start_Event, Timer_Asset_Id, "
		"Timer_Time, Ui_Order FROM achievement_criteria_dbc ORDER BY ID"
	)
	rows = cur.fetchall()
	lines = ["AchieverStaticData.criteria = {"]
	for (id_, achievement_id, type_, asset_id, quantity, start_event, start_asset, fail_event,
			fail_asset, description, flags, timer_start_event, timer_asset_id, timer_time, ui_order) in rows:
		lines.append(
			f"\t[{id_}] = {{\n"
			f"\t\tachievementId = {lua_number(achievement_id)}, type = {lua_number(type_)}, "
			f"assetId = {lua_number(asset_id)}, quantity = {lua_number(quantity)},\n"
			f"\t\tstartEvent = {lua_number(start_event)}, startAsset = {lua_number(start_asset)}, "
			f"failEvent = {lua_number(fail_event)}, failAsset = {lua_number(fail_asset)},\n"
			f"\t\tdescription = {lua_string(description)},\n"
			f"\t\tflags = {lua_number(flags)}, timerStartEvent = {lua_number(timer_start_event)}, "
			f"timerAssetId = {lua_number(timer_asset_id)}, timerTime = {lua_number(timer_time)}, "
			f"uiOrder = {lua_number(ui_order)}\n"
			f"\t}},"
		)
	lines.append("}")
	write_file("Criteria.lua", "achievement_criteria_dbc", len(rows), lines)


def export_criteria_data(cur):
	cur.execute("SELECT criteria_id, type, value1, value2, ScriptName FROM achievement_criteria_data ORDER BY criteria_id, type")
	rows = cur.fetchall()
	grouped = {}
	for criteria_id, type_, value1, value2, script_name in rows:
		grouped.setdefault(criteria_id, []).append((type_, value1, value2, script_name))

	lines = ["AchieverStaticData.criteriaData = {"]
	for criteria_id in sorted(grouped.keys()):
		lines.append(f"\t[{criteria_id}] = {{")
		for type_, value1, value2, script_name in grouped[criteria_id]:
			lines.append(
				f"\t\t{{ type = {lua_number(type_)}, value1 = {lua_number(value1)}, "
				f"value2 = {lua_number(value2)}, scriptName = {lua_string(script_name)} }},"
			)
		lines.append("\t},")
	lines.append("}")
	write_file("CriteriaData.lua", "achievement_criteria_data", len(rows), lines)


def export_rewards(cur):
	cur.execute("SELECT ID, TitleA, TitleH, ItemID, Sender, Subject, Body, MailTemplateID FROM achievement_reward ORDER BY ID")
	rows = cur.fetchall()
	lines = ["AchieverStaticData.rewards = {"]
	for id_, title_a, title_h, item_id, sender, subject, body, mail_template_id in rows:
		lines.append(
			f"\t[{id_}] = {{ titleA = {lua_number(title_a)}, titleH = {lua_number(title_h)}, "
			f"itemId = {lua_number(item_id)}, sender = {lua_number(sender)}, "
			f"mailTemplateId = {lua_number(mail_template_id)},\n"
			f"\t\tsubject = {lua_string(subject)}, body = {lua_string(body)} }},"
		)
	lines.append("}")
	write_file("Rewards.lua", "achievement_reward", len(rows), lines)


def export_reward_locales(cur):
	cur.execute("SELECT ID, Locale, Subject, Text FROM achievement_reward_locale ORDER BY ID, Locale")
	rows = cur.fetchall()
	grouped = {}
	for id_, locale, subject, text in rows:
		grouped.setdefault(id_, {})[locale] = (subject, text)

	lines = ["AchieverStaticData.rewardLocales = {"]
	for id_ in sorted(grouped.keys()):
		lines.append(f"\t[{id_}] = {{")
		for locale in sorted(grouped[id_].keys()):
			subject, text = grouped[id_][locale]
			lines.append(f"\t\t{locale} = {{ subject = {lua_string(subject)}, text = {lua_string(text)} }},")
		lines.append("\t},")
	lines.append("}")
	write_file("RewardLocales.lua", "achievement_reward_locale", len(rows), lines)


def main():
	conn = connect()
	try:
		cur = conn.cursor()
		# Patch-based filtering disabled for now -- export everything
		# regardless of patch (get_excluded_categories is still here to
		# re-enable later if post-Classic content needs excluding again).
		excluded_categories = set()
		export_categories(cur, excluded_categories)
		export_achievements(cur, excluded_categories)
		export_criteria(cur)
		export_criteria_data(cur)
		export_rewards(cur)
		export_reward_locales(cur)
	finally:
		conn.close()


if __name__ == "__main__":
	main()
